[project]
name = "sad2-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boolean-py>=5.0",
    "matplotlib>=3.10.8",
    "networkx>=3.4.2",
    "pytest>=9.0.2",
]
